---
- hosts: all

  tasks:

  - name: add some handy packages
    apt: pkg=$item state=installed update_cache=yes
    with_items:
    - libapache-mod-security
    - apache2-mpm-prefork
    - curl
    - libwww-perl
    - libmime-lite-perl
    
  - name: install modsecurity conf
    copy: src=files/modsecurity.conf dest=/etc/apache2/conf.d/modsecurity.conf owner=root group=root
    
  - name: enable modsecurity module
    command: a2enmod mod-security
    
  - name: put www files in place
    copy: src=$item dest=/var/www/
    with_fileglob: files/www/*
    
  - name: install upload inspect
    copy: src=files/byte-webserver-inspect-uploaded-file dest=/usr/sbin/byte-webserver-inspect-uploaded-file mode=755
    
  - name: restart apache
    service: name=apache2 state=restarted
    
  - include: tests.yml
